---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ggplot2)
library(tidyverse)
library(reshape2)
library(lubridate)
library(viridis)
library(data.table)
library(forcats)
library(RColorBrewer)
```

```{r}
invert_all <- read_csv("eelgrasscompileddatechange.csv")
invert_all$date <- as.Date(invert_all$date, format = "%d-%h-%y")
invert_all_comp <- invert_all %>%
     filter(comp == 1)

invert_all_comp$eel <- as.numeric(invert_all_comp$eel)

invert_all_comp <- invert_all_comp %>% 
  mutate(rel_abun_per = rel_abun*100) 

(invert_all_comp <- invert_all_comp %>% 
  mutate(eel = ifelse(eel == 1, "Eelgrass", eel)))

invert_all_comp <- invert_all_comp %>% 
  mutate(eel = ifelse(eel == 0, "Non Eelgrass", eel))

```

```{r}
coul <- brewer.pal(9, "Set1")
coul <- colorRampPalette(coul)(40)

names <- unique(invert_all_comp$orgnsm)           

names(coul) <- levels(invert_all_comp$orgnsm)

group.colors <- c(Cladoceran = "#E41A1C", Phyllodocida = "#C02E3C", Appendicularia = "#9D435C", Harpac =  "#79577C",  Calanoid = "#566C9C", Brachyura = "#377FB5", Barnacle = "#3C899E", Gammarid = "#409388", Mysida = "#459D71", Cumacea = "#49A75A", Cyclopoid = "#50AA4E", Cnetophora = "#609660", Echinoderm = "#6F8273", Gastropod = "#7E6E85", Valvifera ="#8E5A97", UK4 = "#9F5196", Natantia = "#B55B75", Ostracod = "#CA6553", UK16 = "#DF6F32", UK21 = "#F47910", UK9 = "#FF8C05", UK10 = "#FFA60F", UK13 = "#FFC01A", Caprellidea = "#FFDA24", Fish_Larvae = "#FFF52F", UK11 = "#F3E931", UK12 = "#AC94A0", UK7 = "#E1C62F", Cardidae = "#CFA42D", UK19 = "#BC812A", Bivalvia = "#AA5E28", Pleuronecti = "#B25C3F", UK15 = "#C3655E", UK8 =  "#D36E7D", Euphausiid = "#E4779C", Hyperiidea = "#F47FBB", UK25 = "#E685B8", UK24 = "#D28AB0", UK27 = "#BF8FA8")

```

```{r}
sz_frac_wt <- invert_all_comp %>% 
  select(region,date,sz_frac,rel_abun_per,date,eel) %>% 
  group_by(region,date,eel) %>% 
  summarise(weight_sz_frac = weighted.mean(sz_frac,rel_abun_per))
```

```{r}
q <- ggplot(sz_frac_wt, aes(x= date, y= weight_sz_frac, color= region)) +
  geom_line() + facet_wrap("eel") +
  geom_point(shape = 21, size = 3, fill = "white") +
  theme_bw(base_size=18) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        legend.justification=c(0,1),strip.text.x = element_text(size = 14, colour = "black", face = "bold"), 
          legend.position=c(0,1), legend.title=element_blank()) +
    labs(x= 'Month', y= "Average Size Fraction")

ggsave("sz_frac_compare.png")
q
```



